# Generated by Django 4.1.5 on 2023-01-10 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('username', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=25, null=True)),
                ('password_option', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=25, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
                ('photo', models.FileField(null=True, upload_to='company_user_photo')),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user_login_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
