# Generated by Django 4.1.5 on 2023-01-10 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_company_master_company_user_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_master',
            name='auth_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_Master_auth_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
