# Generated by Django 4.1.5 on 2023-01-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_category',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
