# Generated by Django 4.1.5 on 2023-01-12 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_event_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('image', models.FileField(null=True, upload_to='event_image')),
                ('organizer', models.CharField(max_length=25, null=True)),
                ('responsible', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=25, null=True)),
                ('venue', models.TextField(null=True)),
                ('exhibition_map', models.FileField(null=True, upload_to='exhibition_map')),
                ('limit_registrations', models.BooleanField(default=False)),
                ('limit_registration_no', models.IntegerField(null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_Creation_company_id', to='myapp.company_master')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
