# Generated by Django 4.1.5 on 2023-01-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_event_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_creation',
            name='responsible_person_no',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='event_creation',
            name='responsible',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
