# Generated by Django 4.1.5 on 2023-01-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_event_creation_responsible_person_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_creation',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_Creation_category_id', to='myapp.event_category'),
        ),
    ]
