# Generated by Django 4.1.5 on 2023-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_event_creation_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_creation',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
