# Generated by Django 4.1.5 on 2023-01-12 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0012_event_creation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=25, null=True)),
                ('product', models.CharField(max_length=25, null=True)),
                ('price', models.FloatField(null=True)),
                ('sale_start_dt', models.DateField(null=True)),
                ('sale_end_dt', models.DateField(null=True)),
                ('maximum', models.IntegerField(null=True)),
                ('confirmed', models.IntegerField(null=True)),
                ('unconfirmed', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_ticket_event_id', to='myapp.company_master')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event_selection_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=25, null=True)),
                ('Event_question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_selection_question_question_id', to='myapp.company_master')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('question_type', models.CharField(choices=[('Selection', 'Selection'), ('Text Input', 'Text Input')], max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_question_event_id', to='myapp.company_master')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
