# Generated by Django 4.1.5 on 2023-01-12 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_event_ticket_event_selection_question_event_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_question',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_question_event_id', to='myapp.event_creation'),
        ),
        migrations.AlterField(
            model_name='event_selection_question',
            name='Event_question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_selection_question_question_id', to='myapp.event_creation'),
        ),
        migrations.AlterField(
            model_name='event_ticket',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_ticket_event_id', to='myapp.event_creation'),
        ),
        migrations.CreateModel(
            name='Event_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=25, null=True)),
                ('ticket_instructions', models.CharField(max_length=25, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_note_event_id', to='myapp.event_creation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
