# Generated by Django 4.1.5 on 2023-01-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_event_question_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_selection_question',
            name='Event_question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_selection_question_question_id', to='myapp.event_question'),
        ),
    ]
