# Generated by Django 4.1.5 on 2023-01-23 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_alter_event_selection_question_event_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_account_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('account_name', models.CharField(max_length=55, null=True)),
                ('account_email', models.CharField(max_length=55, null=True)),
                ('business_name', models.CharField(max_length=55, null=True)),
                ('business_type', models.CharField(choices=[('Private Limited', 'Private Limited'), ('Proprietorship', 'Proprietorship'), ('Partnership', 'Partnership'), ('Individual', 'Individual'), ('Public Limited', 'Public Limited'), ('LLP', 'LLP'), ('Trust', 'Trust'), ('Society', 'Society'), ('NGO', 'NGO')], max_length=25, null=True)),
                ('branh_ifsc_code', models.CharField(max_length=25, null=True)),
                ('account_no', models.CharField(max_length=25, null=True)),
                ('re_account_no', models.CharField(max_length=25, null=True)),
                ('beneficiary_name', models.CharField(max_length=25, null=True)),
                ('account_verifly_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
