# Generated by Django 4.1.5 on 2023-01-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_bank_account_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account_master',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bank_account_master_company_id', to='myapp.company_master'),
        ),
    ]
