# Generated by Django 4.1.5 on 2023-01-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_notification_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_id', to='myapp.company_master'),
        ),
    ]
