# Generated by Django 4.1.5 on 2023-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_notification_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account_master',
            name='account_id',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
