# Generated by Django 4.1.5 on 2023-01-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_event_booking_user_data_ticket_confirm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_booking_user_data',
            name='event_creation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_Booking_user_Data_event_id', to='myapp.event_creation'),
        ),
        migrations.AlterField(
            model_name='event_booking_user_data',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_Booking_user_Data_bookig_table_id', to='myapp.event_booking_table'),
        ),
    ]
