# Generated by Django 4.1.5 on 2023-01-25 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0025_alter_event_booking_user_data_event_creation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_booking_user_question_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('event_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_booking_user_question_table_user_id', to='myapp.event_booking_user_data')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_booking_user_question_table_question_id', to='myapp.event_question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
