# Generated by Django 4.1.5 on 2023-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_event_booking_user_question_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_booking_user_data',
            name='confirm_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirm', 'confirm'), ('cancel', 'cancel')], default='pending', max_length=255),
        ),
    ]
