# Generated by Django 4.1.5 on 2023-01-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_event_booking_user_data_confirm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_booking_user_data',
            name='confirm_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirm', 'confirm'), ('cancel', 'cancel'), ('attended', 'attended')], default='pending', max_length=255),
        ),
    ]
