# Generated by Django 4.1.5 on 2023-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_booth_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth_category_type',
            name='sponser_status',
            field=models.BooleanField(default=False),
        ),
    ]
